services:
  fitlife-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - AIVEN_DB_HOST=${AIVEN_DB_HOST}
      - AIVEN_DB_PORT=${AIVEN_DB_PORT}
      - AIVEN_DB_NAME=${AIVEN_DB_NAME}
      - AIVEN_DB_USER=${AIVEN_DB_USER}
      - AIVEN_DB_PASSWORD=${AIVEN_DB_PASSWORD}
      - AIVEN_DB_SSLMODE=${AIVEN_DB_SSLMODE}
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8000
